// MCP Tools — Clientes
module.exports = [
  {
    name: 'clientes_listar',
    description: 'Listar clientes con búsqueda y paginación',
    method: 'GET',
    path: '/api/clientes',
    params: {
      page: { type: 'number', description: 'Número de página' },
      limit: { type: 'number', description: 'Clientes por página' },
      buscar: { type: 'string', description: 'Buscar por nombre, CUIT o código' },
      solo_dni: { type: 'boolean', description: 'Buscar solo por DNI/CUIT' },
    },
    queryParams: ['page', 'limit', 'buscar', 'solo_dni'],
  },
  {
    name: 'clientes_detalle',
    description: 'Obtener detalle de un cliente por su ID',
    method: 'GET',
    path: '/api/clientes/:id',
    params: {
      id: { type: 'string', description: 'ID del cliente', required: true },
    },
  },
  {
    name: 'clientes_crear',
    description: 'Crear un nuevo cliente (se exporta automáticamente a Centum)',
    method: 'POST',
    path: '/api/clientes',
    params: {
      razon_social: { type: 'string', description: 'Razón social / nombre', required: true },
      cuit: { type: 'string', description: 'CUIT/DNI del cliente', required: true },
      condicion_iva: { type: 'string', description: 'Condición ante IVA', required: true, enum: ['CF', 'RI', 'MT', 'EX'] },
      direccion: { type: 'string', description: 'Dirección' },
      localidad: { type: 'string', description: 'Localidad' },
      codigo_postal: { type: 'string', description: 'Código postal' },
      provincia: { type: 'string', description: 'Provincia' },
      telefono: { type: 'string', description: 'Teléfono' },
      email: { type: 'string', description: 'Email' },
      celular: { type: 'string', description: 'Celular' },
      grupo_descuento_id: { type: 'string', description: 'ID del grupo de descuento' },
    },
  },
  {
    name: 'clientes_editar',
    description: 'Editar datos de un cliente',
    method: 'PUT',
    path: '/api/clientes/:id',
    params: {
      id: { type: 'string', description: 'ID del cliente', required: true },
      razon_social: { type: 'string', description: 'Razón social' },
      cuit: { type: 'string', description: 'CUIT/DNI' },
      condicion_iva: { type: 'string', description: 'Condición IVA' },
      direccion: { type: 'string', description: 'Dirección' },
      localidad: { type: 'string', description: 'Localidad' },
      telefono: { type: 'string', description: 'Teléfono' },
      email: { type: 'string', description: 'Email' },
      celular: { type: 'string', description: 'Celular' },
      grupo_descuento_id: { type: 'string', description: 'ID grupo descuento' },
    },
  },
  {
    name: 'clientes_editar_centum',
    description: 'Editar cliente y sincronizar cambios con Centum ERP',
    method: 'PUT',
    path: '/api/clientes/editar-centum/:idCentum',
    params: {
      idCentum: { type: 'string', description: 'ID del cliente en Centum', required: true },
      razon_social: { type: 'string', description: 'Razón social' },
      cuit: { type: 'string', description: 'CUIT/DNI' },
      condicion_iva: { type: 'string', description: 'Condición IVA' },
      direccion: { type: 'string', description: 'Dirección' },
      localidad: { type: 'string', description: 'Localidad' },
      codigo_postal: { type: 'string', description: 'CP' },
      telefono: { type: 'string', description: 'Teléfono' },
      email: { type: 'string', description: 'Email' },
      celular: { type: 'string', description: 'Celular' },
      grupo_descuento_id: { type: 'string', description: 'ID grupo descuento' },
    },
  },
  {
    name: 'clientes_actualizar_contacto',
    description: 'Actualizar email/celular de un cliente (solo local)',
    method: 'PUT',
    path: '/api/clientes/contacto/:idCentum',
    params: {
      idCentum: { type: 'string', description: 'ID del cliente en Centum', required: true },
      email: { type: 'string', description: 'Nuevo email' },
      celular: { type: 'string', description: 'Nuevo celular' },
    },
  },
  {
    name: 'clientes_buscar_afip',
    description: 'Buscar datos de un CUIT en AFIP/ARCA',
    method: 'GET',
    path: '/api/clientes/buscar-afip',
    params: {
      cuit: { type: 'string', description: 'CUIT a buscar', required: true },
    },
    queryParams: ['cuit'],
  },
  {
    name: 'clientes_buscar_centum',
    description: 'Buscar un cliente en Centum BI por CUIT',
    method: 'GET',
    path: '/api/clientes/buscar-centum',
    params: {
      cuit: { type: 'string', description: 'CUIT a buscar', required: true },
    },
    queryParams: ['cuit'],
  },
  {
    name: 'clientes_refresh',
    description: 'Refrescar datos de un cliente desde Centum BI',
    method: 'GET',
    path: '/api/clientes/refresh/:idCentum',
    params: {
      idCentum: { type: 'string', description: 'ID del cliente en Centum', required: true },
    },
  },
  {
    name: 'clientes_importar_centum',
    description: 'Importar un cliente existente de Centum al sistema local',
    method: 'POST',
    path: '/api/clientes/importar-centum',
    params: {
      id_centum: { type: 'number', description: 'ID del cliente en Centum', required: true },
      razon_social: { type: 'string', description: 'Razón social' },
      cuit: { type: 'string', description: 'CUIT' },
      direccion: { type: 'string', description: 'Dirección' },
      localidad: { type: 'string', description: 'Localidad' },
      telefono: { type: 'string', description: 'Teléfono' },
    },
  },
  {
    name: 'clientes_sincronizar_centum',
    description: 'Importar masivamente todos los clientes desde Centum',
    method: 'POST',
    path: '/api/clientes/sincronizar-centum',
    params: {},
  },
  {
    name: 'clientes_duplicados',
    description: 'Encontrar clientes duplicados (por id_centum o CUIT)',
    method: 'GET',
    path: '/api/clientes/duplicados',
    params: {},
  },
  {
    name: 'clientes_direcciones',
    description: 'Obtener direcciones de entrega de un cliente',
    method: 'GET',
    path: '/api/clientes/:id/direcciones',
    params: {
      id: { type: 'string', description: 'ID del cliente', required: true },
    },
  },
  {
    name: 'clientes_agregar_direccion',
    description: 'Agregar una dirección de entrega a un cliente',
    method: 'POST',
    path: '/api/clientes/:id/direcciones',
    params: {
      id: { type: 'string', description: 'ID del cliente', required: true },
      direccion: { type: 'string', description: 'Dirección completa', required: true },
      localidad: { type: 'string', description: 'Localidad' },
      observaciones: { type: 'string', description: 'Observaciones' },
    },
  },
  {
    name: 'clientes_exportar_centum',
    description: 'Exportar un cliente local a Centum ERP',
    method: 'POST',
    path: '/api/clientes/:id/exportar-centum',
    params: {
      id: { type: 'string', description: 'ID del cliente', required: true },
    },
  },
  {
    name: 'clientes_afip_status',
    description: 'Ver estado de la configuración AFIP',
    method: 'GET',
    path: '/api/clientes/afip-status',
    params: {},
  },
]
