// MCP Tools — Compras
module.exports = [
  {
    name: 'compras_dashboard',
    description: 'Dashboard del módulo de compras',
    method: 'GET',
    path: '/api/compras/dashboard',
    params: {},
  },
  {
    name: 'compras_listar_proveedores',
    description: 'Listar proveedores',
    method: 'GET',
    path: '/api/compras/proveedores',
    params: {},
  },
  {
    name: 'compras_detalle_proveedor',
    description: 'Detalle de un proveedor',
    method: 'GET',
    path: '/api/compras/proveedores/:id',
    params: {
      id: { type: 'string', description: 'ID del proveedor', required: true },
    },
  },
  {
    name: 'compras_crear_proveedor',
    description: 'Crear un nuevo proveedor',
    method: 'POST',
    path: '/api/compras/proveedores',
    params: {
      nombre: { type: 'string', description: 'Nombre del proveedor', required: true },
      cuit: { type: 'string', description: 'CUIT' },
      codigo: { type: 'string', description: 'Código interno' },
      lead_time_dias: { type: 'number', description: 'Lead time en días' },
      lead_time_variabilidad_dias: { type: 'number', description: 'Variabilidad del lead time' },
      dias_pedido: { type: 'array', description: 'Días en que se puede pedir [1-7]' },
      contacto: { type: 'string', description: 'Nombre de contacto' },
      telefono: { type: 'string', description: 'Teléfono' },
      email: { type: 'string', description: 'Email' },
      whatsapp: { type: 'string', description: 'WhatsApp' },
      monto_minimo: { type: 'number', description: 'Monto mínimo de pedido' },
      notas: { type: 'string', description: 'Notas' },
    },
  },
  {
    name: 'compras_editar_proveedor',
    description: 'Editar un proveedor',
    method: 'PUT',
    path: '/api/compras/proveedores/:id',
    params: {
      id: { type: 'string', description: 'ID del proveedor', required: true },
      nombre: { type: 'string', description: 'Nombre' },
      cuit: { type: 'string', description: 'CUIT' },
      codigo: { type: 'string', description: 'Código' },
      lead_time_dias: { type: 'number', description: 'Lead time' },
      dias_pedido: { type: 'array', description: 'Días de pedido' },
      contacto: { type: 'string', description: 'Contacto' },
      telefono: { type: 'string', description: 'Teléfono' },
      email: { type: 'string', description: 'Email' },
      whatsapp: { type: 'string', description: 'WhatsApp' },
      monto_minimo: { type: 'number', description: 'Monto mínimo' },
      notas: { type: 'string', description: 'Notas' },
      activo: { type: 'boolean', description: 'Activo/inactivo' },
    },
  },
  {
    name: 'compras_articulos_proveedor',
    description: 'Artículos asociados a un proveedor',
    method: 'GET',
    path: '/api/compras/proveedores/:id/articulos',
    params: {
      id: { type: 'string', description: 'ID del proveedor', required: true },
    },
  },
  {
    name: 'compras_vincular_articulo',
    description: 'Vincular un artículo a un proveedor',
    method: 'POST',
    path: '/api/compras/proveedores/:id/articulos',
    params: {
      id: { type: 'string', description: 'ID del proveedor', required: true },
      articulo_id: { type: 'string', description: 'ID del artículo', required: true },
      unidad_compra: { type: 'string', description: 'Unidad de compra' },
      factor_conversion: { type: 'number', description: 'Factor de conversión' },
      codigo_proveedor: { type: 'string', description: 'Código del proveedor para este artículo' },
      precio_compra: { type: 'number', description: 'Precio de compra' },
      es_principal: { type: 'boolean', description: 'Es proveedor principal de este artículo' },
    },
  },
  {
    name: 'compras_listar_ordenes',
    description: 'Listar órdenes de compra con filtros',
    method: 'GET',
    path: '/api/compras/ordenes',
    params: {
      estado: { type: 'string', description: 'Filtrar por estado' },
      proveedor_id: { type: 'string', description: 'Filtrar por proveedor' },
      desde: { type: 'string', description: 'Fecha desde' },
      hasta: { type: 'string', description: 'Fecha hasta' },
    },
    queryParams: ['estado', 'proveedor_id', 'desde', 'hasta'],
  },
  {
    name: 'compras_detalle_orden',
    description: 'Detalle de una orden de compra',
    method: 'GET',
    path: '/api/compras/ordenes/:id',
    params: {
      id: { type: 'string', description: 'ID de la orden', required: true },
    },
  },
  {
    name: 'compras_crear_orden',
    description: 'Crear una orden de compra',
    method: 'POST',
    path: '/api/compras/ordenes',
    params: {
      proveedor_id: { type: 'string', description: 'ID del proveedor', required: true },
      items: { type: 'array', description: 'Items [{articulo_id, cantidad, precio_unitario}]', required: true },
      notas: { type: 'string', description: 'Notas' },
      fecha_entrega_esperada: { type: 'string', description: 'Fecha entrega esperada' },
      metodo_envio: { type: 'string', description: 'Método de envío' },
    },
  },
  {
    name: 'compras_editar_orden',
    description: 'Editar una orden de compra',
    method: 'PUT',
    path: '/api/compras/ordenes/:id',
    params: {
      id: { type: 'string', description: 'ID de la orden', required: true },
      items: { type: 'array', description: 'Items actualizados' },
      notas: { type: 'string', description: 'Notas' },
      fecha_entrega_esperada: { type: 'string', description: 'Fecha entrega' },
      metodo_envio: { type: 'string', description: 'Método de envío' },
    },
  },
  {
    name: 'compras_enviar_orden',
    description: 'Enviar/confirmar una orden de compra al proveedor',
    method: 'PUT',
    path: '/api/compras/ordenes/:id/enviar',
    params: {
      id: { type: 'string', description: 'ID de la orden', required: true },
    },
  },
  {
    name: 'compras_cancelar_orden',
    description: 'Cancelar una orden de compra',
    method: 'DELETE',
    path: '/api/compras/ordenes/:id',
    params: {
      id: { type: 'string', description: 'ID de la orden', required: true },
    },
  },
  {
    name: 'compras_demanda',
    description: 'Análisis de demanda para un proveedor',
    method: 'GET',
    path: '/api/compras/demanda/:proveedorId',
    params: {
      proveedorId: { type: 'string', description: 'ID del proveedor', required: true },
    },
  },
  {
    name: 'compras_orden_sugerida',
    description: 'Generar orden de compra sugerida por IA',
    method: 'POST',
    path: '/api/compras/orden-sugerida/:proveedorId',
    params: {
      proveedorId: { type: 'string', description: 'ID del proveedor', required: true },
    },
  },
  {
    name: 'compras_chat',
    description: 'Chat con IA sobre el módulo de compras',
    method: 'POST',
    path: '/api/compras/chat',
    params: {
      mensaje: { type: 'string', description: 'Mensaje/pregunta', required: true },
      historial: { type: 'array', description: 'Historial previo' },
    },
  },
  {
    name: 'compras_consumo_interno',
    description: 'Ver registro de consumo interno',
    method: 'GET',
    path: '/api/compras/consumo-interno',
    params: {},
  },
  {
    name: 'compras_registrar_consumo',
    description: 'Registrar consumo interno de artículo',
    method: 'POST',
    path: '/api/compras/consumo-interno',
    params: {
      articulo_id: { type: 'string', description: 'ID del artículo', required: true },
      cantidad: { type: 'number', description: 'Cantidad consumida', required: true },
      motivo: { type: 'string', description: 'Motivo del consumo' },
    },
  },
  {
    name: 'compras_pedidos_extraordinarios',
    description: 'Listar pedidos extraordinarios',
    method: 'GET',
    path: '/api/compras/pedidos-extraordinarios',
    params: {},
  },
  {
    name: 'compras_crear_pedido_extraordinario',
    description: 'Crear pedido extraordinario',
    method: 'POST',
    path: '/api/compras/pedidos-extraordinarios',
    params: {
      articulo_id: { type: 'string', description: 'ID del artículo' },
      cantidad: { type: 'number', description: 'Cantidad' },
      motivo: { type: 'string', description: 'Motivo' },
      proveedor_id: { type: 'string', description: 'ID del proveedor' },
    },
  },
  {
    name: 'compras_promociones_proveedor',
    description: 'Ver promociones de un proveedor',
    method: 'GET',
    path: '/api/compras/proveedores/:id/promociones',
    params: {
      id: { type: 'string', description: 'ID del proveedor', required: true },
    },
  },
]
