// MCP Tools — POS Ventas
module.exports = [
  {
    name: 'pos_articulos',
    description: 'Obtener artículos disponibles en el POS con búsqueda opcional',
    method: 'GET',
    path: '/api/pos/articulos',
    params: {
      buscar: { type: 'string', description: 'Término de búsqueda' },
    },
    queryParams: ['buscar'],
  },
  {
    name: 'pos_rubros',
    description: 'Obtener rubros/categorías del POS',
    method: 'GET',
    path: '/api/pos/rubros',
    params: {},
  },
  {
    name: 'pos_subrubros',
    description: 'Obtener sub-rubros del POS',
    method: 'GET',
    path: '/api/pos/subrubros',
    params: {},
  },
  {
    name: 'pos_crear_venta',
    description: 'Crear una venta en el POS (genera factura en Centum y AFIP)',
    method: 'POST',
    path: '/api/pos/ventas',
    params: {
      id_cliente_centum: { type: 'number', description: 'ID del cliente en Centum', required: true },
      nombre_cliente: { type: 'string', description: 'Nombre del cliente' },
      items: { type: 'array', description: 'Array de items: [{id_articulo_centum, nombre, cantidad, precio_unitario, subtotal, es_pesable, rubro}]', required: true },
      subtotal: { type: 'number', description: 'Subtotal de la venta', required: true },
      descuento_total: { type: 'number', description: 'Descuento total aplicado' },
      total: { type: 'number', description: 'Total final de la venta', required: true },
      monto_pagado: { type: 'number', description: 'Monto pagado por el cliente', required: true },
      vuelto: { type: 'number', description: 'Vuelto a dar' },
      pagos: { type: 'array', description: 'Array de pagos: [{forma_cobro_id, nombre, monto}]', required: true },
      descuento_forma_pago: { type: 'number', description: 'Descuento por forma de pago' },
      promociones_aplicadas: { type: 'array', description: 'Promociones aplicadas' },
      pedido_pos_id: { type: 'string', description: 'ID del pedido POS si es cobro de pedido' },
      saldo_aplicado: { type: 'number', description: 'Saldo de cuenta corriente aplicado' },
      gift_cards_aplicadas: { type: 'array', description: 'Gift cards usadas' },
      gift_cards_a_activar: { type: 'array', description: 'Gift cards a activar' },
      caja_id: { type: 'string', description: 'ID de la caja' },
      canal: { type: 'string', description: 'Canal de venta' },
      descuento_grupo_cliente: { type: 'number', description: 'Descuento por grupo de cliente' },
      grupo_descuento_nombre: { type: 'string', description: 'Nombre del grupo de descuento' },
    },
  },
  {
    name: 'pos_listar_ventas',
    description: 'Listar ventas del POS con filtros opcionales',
    method: 'GET',
    path: '/api/pos/ventas',
    params: {
      numero_factura: { type: 'string', description: 'Buscar por número de factura' },
      buscar: { type: 'string', description: 'Buscar por nombre/CUIT del cliente' },
      fecha: { type: 'string', description: 'Filtrar por fecha (YYYY-MM-DD)' },
      sucursal_id: { type: 'string', description: 'Filtrar por sucursal' },
      cajero_id: { type: 'string', description: 'Filtrar por cajero' },
      articulo: { type: 'string', description: 'Buscar por nombre de artículo' },
      clasificacion: { type: 'string', description: 'Filtrar por clasificación (empresa/prueba)' },
    },
    queryParams: ['numero_factura', 'buscar', 'fecha', 'sucursal_id', 'cajero_id', 'articulo', 'clasificacion'],
  },
  {
    name: 'pos_detalle_venta',
    description: 'Obtener detalle completo de una venta por ID',
    method: 'GET',
    path: '/api/pos/ventas/:id',
    params: {
      id: { type: 'string', description: 'ID de la venta', required: true },
    },
  },
  {
    name: 'pos_cae_venta',
    description: 'Obtener el CAE (autorización AFIP) de una venta',
    method: 'GET',
    path: '/api/pos/ventas/:id/cae',
    params: {
      id: { type: 'string', description: 'ID de la venta', required: true },
    },
  },
  {
    name: 'pos_devoluciones_venta',
    description: 'Obtener notas de crédito/devoluciones de una venta',
    method: 'GET',
    path: '/api/pos/ventas/:id/devoluciones',
    params: {
      id: { type: 'string', description: 'ID de la venta', required: true },
    },
  },
  {
    name: 'pos_enviar_email_venta',
    description: 'Enviar comprobante de venta por email',
    method: 'POST',
    path: '/api/pos/ventas/:id/enviar-email',
    params: {
      id: { type: 'string', description: 'ID de la venta', required: true },
      email: { type: 'string', description: 'Email destino', required: true },
    },
  },
  {
    name: 'pos_eliminar_venta',
    description: 'Eliminar una venta (solo admin)',
    method: 'DELETE',
    path: '/api/pos/ventas/:id',
    params: {
      id: { type: 'string', description: 'ID de la venta', required: true },
    },
  },
  {
    name: 'pos_cambiar_cliente_venta',
    description: 'Cambiar el cliente asignado a una venta',
    method: 'PUT',
    path: '/api/pos/ventas/:id/cliente',
    params: {
      id: { type: 'string', description: 'ID de la venta', required: true },
      id_cliente_centum: { type: 'number', description: 'ID del nuevo cliente en Centum', required: true },
    },
  },
  {
    name: 'pos_reenviar_centum',
    description: 'Reenviar una venta a Centum ERP (si falló previamente)',
    method: 'POST',
    path: '/api/pos/ventas/:id/reenviar-centum',
    params: {
      id: { type: 'string', description: 'ID de la venta', required: true },
    },
  },
  {
    name: 'pos_reporte_promociones',
    description: 'Reporte de promociones aplicadas en ventas (por rango de fechas)',
    method: 'GET',
    path: '/api/pos/ventas/reportes/promociones',
    params: {
      desde: { type: 'string', description: 'Fecha desde (YYYY-MM-DD)' },
      hasta: { type: 'string', description: 'Fecha hasta (YYYY-MM-DD)' },
    },
    queryParams: ['desde', 'hasta'],
  },
]
