// Registro de servicios para monitoreo de salud de APIs
const SERVICE_REGISTRY = [
  {
    id: 'centum_articulos',
    nombre: 'Artículos ERP',
    descripcion: 'Sincronización de artículos desde Centum ERP',
    servicioLog: 'centum_articulos',
    frecuenciaEsperada: 24 * 60, // 24h en minutos
    umbralWarning: 26 * 60,
    umbralCritico: 36 * 60,
    endpointManual: '/api/articulos/sincronizar-erp',
    metodoManual: 'POST',
    tipo: 'cron',
  },
  {
    id: 'centum_stock',
    nombre: 'Stock Depósito',
    descripcion: 'Sincronización de stock desde depósito central',
    servicioLog: 'centum_stock',
    frecuenciaEsperada: 60,
    umbralWarning: 120,
    umbralCritico: 180,
    endpointManual: '/api/articulos/sincronizar-stock',
    metodoManual: 'POST',
    tipo: 'cron',
  },
  {
    id: 'centum_clientes_bi',
    nombre: 'Clientes (BI)',
    descripcion: 'Sync incremental de clientes desde Centum BI',
    servicioLog: 'centum_clientes_bi',
    frecuenciaEsperada: 5,
    umbralWarning: 15,
    umbralCritico: 30,
    endpointManual: '/api/api-logs/sync/clientes-bi',
    metodoManual: 'POST',
    tipo: 'cron',
  },
  {
    id: 'centum_clientes_retry',
    nombre: 'Retry Clientes',
    descripcion: 'Reintento de clientes pendientes de sync a Centum',
    servicioLog: 'centum_clientes_retry',
    frecuenciaEsperada: 5,
    umbralWarning: 15,
    umbralCritico: 30,
    endpointManual: '/api/api-logs/sync/clientes-retry',
    metodoManual: 'POST',
    tipo: 'cron',
  },
  {
    id: 'centum_clientes',
    nombre: 'Clientes (API)',
    descripcion: 'Operaciones de clientes vía API REST de Centum',
    servicioLog: 'centum_clientes',
    frecuenciaEsperada: null,
    umbralWarning: null,
    umbralCritico: null,
    endpointManual: null,
    metodoManual: null,
    tipo: 'on-demand',
  },
  {
    id: 'afip_facturacion',
    nombre: 'AFIP',
    descripcion: 'Facturación electrónica AFIP',
    servicioLog: 'afip_facturacion',
    frecuenciaEsperada: null,
    umbralWarning: null,
    umbralCritico: null,
    endpointManual: null,
    metodoManual: null,
    tipo: 'on-demand',
  },
  {
    id: 'mp_point',
    nombre: 'MP Point',
    descripcion: 'Pagos con Mercado Pago Point',
    servicioLog: 'mp_point',
    frecuenciaEsperada: null,
    umbralWarning: null,
    umbralCritico: null,
    endpointManual: null,
    metodoManual: null,
    tipo: 'on-demand',
  },
  {
    id: 'batch_ia',
    nombre: 'Análisis IA',
    descripcion: 'Análisis batch nocturno de cierres de caja',
    servicioLog: 'batch_ia',
    frecuenciaEsperada: 24 * 60,
    umbralWarning: 26 * 60,
    umbralCritico: 36 * 60,
    endpointManual: null,
    metodoManual: null,
    tipo: 'cron',
  },
]

module.exports = { SERVICE_REGISTRY }
